[package]
name = "kpm"
version = "0.1.0"
authors = ["Pera Pisar <1405223@gmail.com>"]
edition = "2018"

[dependencies]
clipboard = "0.5.0"
notify-rust = "3.6.0"
rand = "0.6.5"
serde = "1.0.93"
serde_derive = "1.0.93"
serde_json = "1.0.39"
xdg = "2.2.0"
